import turtle
turtle.hideturtle()
turtle.setup(800,800)
turtle.circle(50)
turtle.penup()
turtle.goto(130,0)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(260,0)
turtle.pendown()
turtle.circle(50)

turtle.penup()
turtle.goto(65,-50)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(195,-50)
turtle.pendown()
turtle.circle(50)
